### ISSUE TITLE
Correct license?

### ISSUE THREAD

**Issue by eXpl0it3r** [richgel999/miniz#120]
The original [Google Code project](https://code.google.com/archive/p/miniz/) this Git repository is based on, listed miniz as being under Unlicense.

> Completely free: Public domain in jurisdictions that recognize copyright laws, with a license patterned after the public domain SQLite project, see unlicense.org.

But with commit 224d207ce8fffb908e156d27478be3afb5d83e6a @uroni marked the project as MIT licensed with the vague commit comment.

> MiniZ ZIP64 was part of valve vogl which is MIT licensed

Is there a source to that Valve vogl claim?

**Comment by uroni** [comment]
https://github.com/ValveSoftware/vogl/blob/434dcc52b768b4aa32b6ea64e68182daaacb23fc/src/voglcore/vogl_miniz_zip.cpp

https://richg42.blogspot.com/2014/03/zip64-version-of-miniz-library-released.html

**Comment by eXpl0it3r** [comment]
Ah I see, so in theory the MIT would only apply to the ZIP64 part, but I guess it makes sense to mark everything as MIT, which is still a great license. 🙂 

Thanks for the clarification!

**Comment by uroni** [comment]
Also, there may be issues here in Germany with unlicense/disclaiming copyright, so I am happy that Rich licensed it as MIT.

**Comment by icculus** [comment]
Hi, I want to revisit this issue for a moment.

We ( https://github.com/libsdl-org/SDL_image ) are stuck on an older version of miniz, since we don't want to add a second open source license to our project by upgrading our copy of miniz. MIT is not a particularly _bad_ license, however, it _does_ state you need to reprint the license text in your documentation, which would be adding new terms our existing code.

Is there some way we can get this dual-licensed, so it can work for those that prefer (or need) the MIT license, but also for those that prefer (or need!) the public domain option?

Thanks for your consideration here!

**Comment by icculus** [comment]
> Is there some way we can get this dual-licensed, so it can work for those that prefer (or need) the MIT license, but also for those that prefer (or need!) the public domain option?

Is that a no, then? @richgel999, any opinion on this?

**Comment by richgel999** [comment]
I'm totally open to whatever license people need/want, as long as it's legally possible (given that many changes have been integrated into the code, by many people). I think dual licensing should be doable.

**Comment by richgel999** [comment]
> MiniZ ZIP64 was part of valve vogl which is MIT licensed

The ZIP64 portions (not the core code in miniz) should be easily separated out into another file, and that could remain MIT. Then we can dual license the other code, or just leave it as-is. What do you think?

**Comment by richgel999** [comment]
> > Is there some way we can get this dual-licensed, so it can work for those that prefer (or need) the MIT license, but also for those that prefer (or need!) the public domain option?
> 
> Is that a no, then? @richgel999, any opinion on this?

Looking at the code, I believe we would need the other copyright holders to agree to dual license on the entire thing (MIT and unlicense/public domain). We would need Epic Megagames (who holds RAD's IP now), Valve, and anyone else who has contributed to the MIT portion to agree to switch to dual license. It should be possible because it would be good PR for everyone - right?

Tenacious Software is a defunct Texas entity legally, so I will consult my Texas attorney on the matter since this was a Texas LLC.

**Comment by icculus** [comment]
> The ZIP64 portions (not the core code in miniz) should be easily separated out into another file, and that could remain MIT. Then we can dual license the other code, or just leave it as-is. What do you think?

That would be perfect for me, honestly.

**Comment by icculus** [comment]
> We would need Epic Megagames (who holds RAD's IP now)

I can ping Mike Sartain, who is at Epic now, unless you have a better contact. Let me know if you want me to poke anyone.

**Comment by richgel999** [comment]
> > We would need Epic Megagames (who holds RAD's IP now)
> 
> I can ping Mike Sartain, who is at Epic now, unless you have a better contact. Let me know if you want me to poke anyone.

Thanks that's great. Could you also please ping Valve? May need to ping the mighty GabeN himself. I'll look at the licenses and see who else we need to ping, that I should be able to handle.

**Comment by icculus** [comment]
I'll get the ball rolling with Valve, too, and report back.

**Comment by 8bitprodigy** [comment]
> I'll get the ball rolling with Valve, too, and report back.

Any update to this? The Readme.md says it's MIT-licensed, and the source file has MIT at the top and unlicense at the bottom, still, and it's 4 years later.
