### ISSUE TITLE
mz_uncompress with MZ_NO_FLUSH flag

### ISSUE THREAD

**Issue by reliasn** [richgel999/miniz#56]
I wanted to implement these 2 simple functions:
```c++
string mCompress(string content);
string mUncompress(string content);
```
by simply using the mz_compress/mz_uncompress functions.
For ``mCompress``, I came up with this working solution:
```c++
string mCompress(string content){
    int src_len = content.size();
    unsigned long cmp_len = mz_compressBound(src_len);
    unsigned char *pCmp = (unsigned char *)malloc((size_t)cmp_len);
    string ret;
    int cmp_status = mz_compress(pCmp, &cmp_len, (const unsigned char *)content.c_str(), src_len);
    if(cmp_status == Z_OK){
        ret = string((char*)pCmp, cmp_len);
    }
    free(pCmp);
    return ret;
}
```
But for ``mUncompress``, things got more complicated because the current implementation of ``mz_uncompress`` uses the ``MZ_FINISH`` flag which, according to the documentation, ``implies that the input and output buffers are large enough to hold the entire compressed/decompressed file``. The problem with this approach is that sometimes you don't know the buffer size that you need to allocate when uncompressing an unknown compressed string. So I came up with this solution:
```c++
int xuncompress(unsigned char **pDest, mz_ulong *pDest_len, const unsigned char *pSource, mz_ulong source_len){
    mz_stream stream;
    int status, bufLen = *pDest_len;
    memset(&stream, 0, sizeof(stream));

    // In case mz_ulong is 64-bits (argh I hate longs).
    if ((source_len | *pDest_len) > 0xFFFFFFFFU) return MZ_PARAM_ERROR;

    stream.next_in = pSource;
    stream.avail_in = (mz_uint32)source_len;
    stream.next_out = *pDest;
    stream.avail_out = (mz_uint32)bufLen;

    status = mz_inflateInit(&stream);
    if (status != MZ_OK)
        return status;

    while(status == MZ_OK){
        status = mz_inflate(&stream, MZ_NO_FLUSH);
        if(status == MZ_OK){   // if status == MZ_STREAM_END, we don't need to realloc anymore
            bufLen += *pDest_len;
            *pDest = (unsigned char *)realloc(*pDest, bufLen);
            stream.next_out = *pDest + stream.total_out;
            stream.avail_out = bufLen - stream.total_out;
        }
    }
    *pDest_len = stream.total_out;

    return mz_inflateEnd(&stream);
}

string mUncompress(string content){
    int src_len = content.size();
    unsigned long cmp_len = src_len * 2;
    unsigned char *pCmp = (unsigned char *)malloc((size_t)cmp_len);
    string ret;
    int cmp_status = xuncompress(&pCmp, &cmp_len, (const unsigned char *)content.c_str(), src_len);
    if(cmp_status == Z_OK){
        ret = string((char*)pCmp, cmp_len);
    }
    free(pCmp);
    return ret;
}
```
``xuncompress`` is similar to ``mz_uncompress``, but it calls ``mz_inflate`` with the ``MZ_NO_FLUSH`` flag and ``realloc``'s the buffer by incrementing with the initial ``*pDest_len`` that was passed into the function.

This works great and I'm able to handle compression/uncompression properly when my application communicates with my Node.js server (where I use the zlib module to compress/uncompress). However, I'm a bit skeptical about my implementation. Anyways, I'd appreciate if anyone could give me any inputs on how to improve this or even if there's a better solution that I haven't found yet. 

Thanks!

**Comment by paulharris** [comment]
Yes, you are right to allocate and extract in chunks, unless you can *guarantee* that the output will be a known size (ie store the uncompressed size with the compressed data).

You don't need to alloc a separate char array and realloc.  And you are reallocing a lot more often than you really need to.

There are 2 other approaches you could take.

1) Decompress directly into the string.
Use str.resize(bigger_size); each time,
and the output pointer is simply &str[next_char]
At the end, you can str.resize(final_size), and you can use the swap trick to free any excess reserve memory.
* No extra char alloc
* Allow std::string to manage the realloc (it will grow by something like 1.5x each resize to try and anticipate future growth - factor decided by library implementer)
* Just one function
* To reduce the reallocations required, init the string with an initial size guess... str.reserve(1024) will skip a lot of the small initial resizes.  If its likely to be a megabyte of data, then str.reserve(1024*1024).
* If you *dont* do the swap trick, then you can allow the caller to pass in the string by reference, which means the caller can decompress thousands of independent blocks into one output string, thus skipping most of the reallocs - can be a lot more efficient.  ie once string has reserved the memory then the resize just fiddles the size member variable, no actual reallocs.

2) Decompress into a memory block on the stack.
char buffer[1024];
then set the output pointers to buffer.
Each time you decompress, then resize and copy the results to the string.
* If you don't need to store the results, you don't have to copy the results out.  You could use it to figure out what the actual decompressed size is without storing the results.  Important if reallocs are not possible.
* Instead of copying to string, you can call a function with the results... ie like transform(begin,end,out) style.

**Comment by reliasn** [comment]
I went ahead and decided to use the 2nd approach that you suggested:
```c
int xuncompressNew(const unsigned char *pSource, mz_ulong source_len, string *ret){
    mz_stream stream;
    memset(&stream, 0, sizeof(stream));

    // In case mz_ulong is 64-bits (argh I hate longs).
    if (source_len > 0xFFFFFFFFU) return MZ_PARAM_ERROR;

    stream.next_in = pSource;
    stream.avail_in = (mz_uint32)source_len;

    int status = mz_inflateInit(&stream);
    if (status != MZ_OK)
        return status;

    while(status == MZ_OK){
        unsigned char buffer[100];
        stream.next_out = buffer;
        stream.avail_out = sizeof(buffer);
        status = mz_inflate(&stream, MZ_NO_FLUSH);
        if(status == MZ_STREAM_END || status == MZ_OK){
            ret->append((char*)buffer, stream.total_out - ret->size());
        }
    }

    mz_inflateEnd(&stream);
    return status;
}
```
The buffer size is set at 100 just to test with my string which has a length of 490 uncompressed. I monitored the size of the compressed messages that I was receiving from my Node.js server and they all have an average of 3600 bytes. So setting the buffer to 1024 or even 3600 will obviously reduce the number of times that ``mz_inflate`` is called.

Thanks for the inputs! I haven't monitored yet if there were any performance improvements, but it already helps a lot the fact that the buffer is on the stack and I don't need to worry about alloc'ing and free'ing blocks of memory.

**Comment by paulharris** [comment]
Cool
Note that I'd typically pass in the string "ret" as a reference, not a pointer.
If you pass as a pointer... then, do you check if its a null pointer?
A reference ensures that a valid string has been given to the function.

Also, I was looking at the comment you made "In case mz_ulong is 64-bits (argh I hate longs)."

I assume avail_in is only 32 bit, so I can see you are casting to 32 and blocking if > 32 bit...
but, I would also assume that avail_in and the input buffer can also be adjusted to feed the mz functions more input data.   ie this library will be able to support streaming data in chunk by chunk...
So just feed it X bytes from the source input... where X < max_32bit and X < source_len
ie X = min(max_32bit, source_len)... then do a loop until the input buffer is exhausted.

If you really want to restrict to 32 bit inputs, then make it explicit in the input params... only accept 32 bit source len...

**Comment by reliasn** [comment]
That comment was [made by the author](https://github.com/richgel999/miniz/blob/master/miniz.c#L1137) and I forgot to remove it.

I'm working on 32-bit only so that check isn't currently needed. But your point is valid 😄
